import { Container } from '@/components/layout/Container';

export const metadata = {
  title: 'Terms of Service - DevTools Hub',
  description: 'Terms of service for DevTools Hub',
};

export default function TermsPage() {
  return (
    <div className="py-12">
      <Container>
        <div className="max-w-3xl mx-auto prose prose-slate">
          <h1>Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>

          <h2>Agreement to Terms</h2>
          <p>
            By accessing and using DevTools Hub, you agree to be bound by these Terms of Service and all applicable
            laws and regulations.
          </p>

          <h2>Use License</h2>
          <p>
            Permission is granted to use our tools for personal and commercial purposes. This license shall
            automatically terminate if you violate any of these restrictions.
          </p>

          <h2>Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use our services for any illegal purpose</li>
            <li>Attempt to bypass rate limits or security measures</li>
            <li>Abuse or overload our systems</li>
            <li>Scrape or automatically access our services</li>
            <li>Use our AI tools to generate harmful, illegal, or inappropriate content</li>
          </ul>

          <h2>Rate Limits</h2>
          <p>
            AI tools are subject to rate limits. Free users are limited to 3 generations per day per tool. We reserve
            the right to modify these limits at any time.
          </p>

          <h2>Service Availability</h2>
          <p>
            We strive to maintain high availability but do not guarantee uninterrupted access. We may modify, suspend,
            or discontinue any part of our services at any time.
          </p>

          <h2>Disclaimer</h2>
          <p>
            Our tools are provided "as is" without warranties of any kind. We do not guarantee the accuracy,
            completeness, or usefulness of any information or results generated by our tools.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            DevTools Hub shall not be liable for any damages arising from the use or inability to use our services,
            including but not limited to data loss, business interruption, or other commercial damages.
          </p>

          <h2>AI-Generated Content</h2>
          <p>
            Content generated by our AI tools is provided for informational purposes only. You are responsible for
            reviewing and verifying any AI-generated content before use. We do not claim ownership of AI-generated
            content.
          </p>

          <h2>Intellectual Property</h2>
          <p>
            The design, code, and content of DevTools Hub are protected by copyright and other intellectual property
            laws. You may not copy, modify, or distribute our website code without permission.
          </p>

          <h2>Privacy</h2>
          <p>
            Your use of our services is also governed by our Privacy Policy. Please review our Privacy Policy to
            understand our practices.
          </p>

          <h2>Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of our services after changes
            constitutes acceptance of the new terms.
          </p>

          <h2>Governing Law</h2>
          <p>
            These terms shall be governed by and construed in accordance with applicable laws, without regard to
            conflict of law provisions.
          </p>

          <h2>Contact</h2>
          <p>
            If you have questions about these Terms of Service, please contact us through our website.
          </p>
        </div>
      </Container>
    </div>
  );
}
